# Generated by Django 5.2.7 on 2025-10-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=512, verbose_name='檔案名稱')),
                ('file_path', models.CharField(max_length=1024, verbose_name='檔案路徑')),
                ('file_type', models.CharField(max_length=32, verbose_name='檔案類型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '處理中'), ('completed', '已完成'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='狀態')),
                ('total_items', models.IntegerField(default=0, verbose_name='總項目數')),
                ('processed_items', models.IntegerField(default=0, verbose_name='已處理項目數')),
                ('success_items', models.IntegerField(default=0, verbose_name='成功項目數')),
                ('failed_items', models.IntegerField(default=0, verbose_name='失敗項目數')),
                ('error_log', models.TextField(blank=True, verbose_name='錯誤日誌')),
                ('result_summary', models.JSONField(blank=True, default=dict, verbose_name='結果摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
            ],
            options={
                'verbose_name': '匯入工作',
                'verbose_name_plural': '匯入工作',
                'db_table': 'import_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('historical', '歷屆考題'), ('simulation', '模擬考試'), ('mixed', '混合練習'), ('bookmarked', '收藏題庫'), ('wrong', '錯題本')], max_length=20, verbose_name='練習模式')),
                ('status', models.CharField(choices=[('in_progress', '進行中'), ('completed', '已完成'), ('abandoned', '已放棄')], default='in_progress', max_length=20, verbose_name='狀態')),
                ('total_questions', models.IntegerField(verbose_name='題目總數')),
                ('answered_questions', models.IntegerField(default=0, verbose_name='已答題數')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='答對題數')),
                ('difficulty', models.CharField(blank=True, max_length=20, verbose_name='難度')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='開始時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('total_time_spent', models.IntegerField(default=0, verbose_name='總花費時間（秒）')),
            ],
            options={
                'verbose_name': '練習場次',
                'verbose_name_plural': '練習場次',
                'db_table': 'practice_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_number', models.CharField(max_length=32, verbose_name='題號')),
                ('content', models.TextField(verbose_name='題目內容')),
                ('question_type', models.CharField(choices=[('single', '單選題'), ('multiple', '複選題'), ('essay', '申論題'), ('truefalse', '是非題')], default='single', max_length=20, verbose_name='題型')),
                ('difficulty', models.CharField(choices=[('easy', '簡單'), ('medium', '中等'), ('hard', '困難')], default='medium', max_length=20, verbose_name='難度')),
                ('points', models.IntegerField(default=1, verbose_name='配分')),
                ('analysis', models.TextField(blank=True, verbose_name='解析')),
                ('answer_explanation', models.TextField(blank=True, verbose_name='答案說明')),
                ('source_file', models.CharField(blank=True, max_length=512, verbose_name='來源檔案')),
                ('source_page', models.IntegerField(blank=True, null=True, verbose_name='來源頁碼')),
                ('source_url', models.URLField(blank=True, verbose_name='來源網址')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('review', '待審核'), ('published', '已發布'), ('archived', '已封存')], default='draft', max_length=20, verbose_name='狀態')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開')),
                ('view_count', models.IntegerField(default=0, verbose_name='瀏覽次數')),
                ('attempt_count', models.IntegerField(default=0, verbose_name='作答次數')),
                ('correct_count', models.IntegerField(default=0, verbose_name='答對次數')),
                ('version', models.IntegerField(default=1, verbose_name='版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='發布時間')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
            ],
            options={
                'verbose_name': '題目',
                'verbose_name_plural': '題目',
                'db_table': 'questions',
                'ordering': ['exam_session', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_options', models.JSONField(default=list, verbose_name='選擇的選項')),
                ('answer_text', models.TextField(blank=True, verbose_name='作答文字')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正確')),
                ('time_spent', models.IntegerField(default=0, verbose_name='作答時間（秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作答時間')),
            ],
            options={
                'verbose_name': '作答紀錄',
                'verbose_name_plural': '作答紀錄',
                'db_table': 'question_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBookmark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏時間')),
            ],
            options={
                'verbose_name': '題目收藏',
                'verbose_name_plural': '題目收藏',
                'db_table': 'question_bookmarks',
            },
        ),
        migrations.CreateModel(
            name='QuestionNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='筆記內容')),
                ('is_private', models.BooleanField(default=True, verbose_name='私人筆記')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '題目筆記',
                'verbose_name_plural': '題目筆記',
                'db_table': 'question_notes',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option_label', models.CharField(max_length=10, verbose_name='選項標籤')),
                ('content', models.TextField(verbose_name='選項內容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否為正確答案')),
                ('order', models.IntegerField(default=0, verbose_name='選項順序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '題目選項',
                'verbose_name_plural': '題目選項',
                'db_table': 'question_options',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=512, verbose_name='題組標題')),
                ('description', models.TextField(blank=True, verbose_name='題組描述/題幹')),
                ('order', models.IntegerField(default=0, verbose_name='題組順序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '題組',
                'verbose_name_plural': '題組',
                'db_table': 'question_sets',
                'ordering': ['exam_session', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='標籤名稱')),
                ('category', models.CharField(blank=True, max_length=64, verbose_name='標籤分類')),
                ('description', models.TextField(blank=True, verbose_name='標籤說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '題目標籤',
                'verbose_name_plural': '題目標籤',
                'db_table': 'question_tags',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '題目標籤關聯',
                'verbose_name_plural': '題目標籤關聯',
                'db_table': 'question_tag_relations',
            },
        ),
    ]
