# Generated by Django 5.2.7 on 2025-10-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(default='user', max_length=32)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
